name: build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - run: npm ci
      - run: npm run build
      - run: npm run test:ci
      - name: Publish Test Report
        uses: ctrf-io/github-test-reporter@v1.0.12
        with:
          report-path: 'vitest-ctrf/*.json'
          summary: true
          pull-request: true
          summary-report: true
          failed-report: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
